### ISSUE TITLE
Azure Pipelines Driver not starting

### ISSUE THREAD

**Issue by kevin306** [microsoft/WinAppDriver#1588]
I'm unable to successfully run the driver in my azure dev ops env. Getting this error when trying to run my tests after enabling winappdriver task.

`error: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session. The status of the exception was UnknownError, and the message was: No connection could be made because the target machine actively refused it. No connection could be made because the target machine actively refused it`

I am using a Microsoft hosted agent and yaml looks like:

```
- task: Windows Application Driver@0
    inputs:
      OperationType: 'Start'
      AgentResolution: '1080p'

  - task: VSTest@2
    displayName: 'UI Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '$(Build.SourcesDirectory)\**\**\*test.dll'
      searchFolder: '$(Build.SourcesDirectory)'
      platform: '$(platform)'
      configuration: '$(configuration)'
    continueOnError: true

  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Stop'
```

My understanding is for Microsoft hosted agents it should work out of the box but output from winappdriver stop task says it never started.
`Unable to close WinAppDriver.exe due to process not found. WinAppDriver already not running?`

I saw some people mentioning setting interactive mode on the agent but is this required for microsoft hosted ones?

**Comment by anunay1** [comment]
Interactive mode should be ON for Microsoft hosted agents also.

**Comment by kevin306** [comment]
How do I set this, I cant see where in any documentation

**Comment by anunay1** [comment]
check  [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=mstest#visible-ui-testing-using-self-hosted-windows-agents)

**Comment by anunay1** [comment]
@kevin306 let me know if it works with the link that I provided.

**Comment by kevin306** [comment]
@anunay1 But that is for a self hosted agent right. It seems like from log from `winappdriver stop` that the driver never started. Is it installed by default on microsoft hosted agents?

**Comment by anunay1** [comment]
no you need to use the below task to install WinAppDriver
https://marketplace.visualstudio.com/acquisition?itemName=WinAppDriver.winappdriver-pipelines-task

**Comment by anunay1** [comment]
check this [link](https://github.com/microsoft/WinAppDriver/blob/master/Docs/CI_AzureDevOps.md)

**Comment by kevin306** [comment]
Yes so as I mentioned above I have that installed already and is in my yaml

```
- task: Windows Application Driver@0
    inputs:
      OperationType: 'Start'
      AgentResolution: '1080p'

  - task: VSTest@2
    displayName: 'UI Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '$(Build.SourcesDirectory)\**\**\*test.dll'
      searchFolder: '$(Build.SourcesDirectory)'
      platform: '$(platform)'
      configuration: '$(configuration)'
    continueOnError: true

  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Stop'
```

And I am using `windows-latest` as image which I understand has everything setup already to run ui testing correct?
