### ISSUE TITLE
How to start WinAppDriver as a non-admin user

### ISSUE THREAD

**Issue by aries-zhang** [microsoft/WinAppDriver#1983]
Hi team, quite opposite to this issue: https://github.com/microsoft/WinAppDriver/issues/1908, in my use case, the app being tested does not work under elevated permissions, so it has to run as a non-admin user to properly function.

Is there a way to specify a `runAs` user in the WinAppDriver ADO task?

```
  - task: Windows Application Driver@0
    inputs:
      OperationType: Start
      AgentResolution: 1080p
```
